### PR TITLE
Add ChargePoint

### PR DESCRIPTION
**Pull request by vikranthdatta**

### CODE REVIEW

**Review by nglgzz — CHANGES_REQUESTED** [review]
Thank you for your contribution @vikranthdatta!

Could you move your entry so that entries in each category are sorted in alphabetical order?

**Comment by vikranthdatta** [comment]
I'll make the changes to the pull request.

**Comment by vikranthdatta** [comment]
The pull request that i made actually contains all the companies arranged in alphabetical order.i added ChargePoint in the energy section. it was added in the alphabetical order and was added after Bulb.if there are any other changes that i have to make in the pull request please leave a comment.

**Comment by nglgzz** [comment]
From the changes I see you added ChargePoint after Vestas, but as you said should be after Bulb, can you move it after Bulb please?

**Comment by vikranthdatta** [comment]
Ok ,,ill make the changes and add a new pull request

**Comment by vikranthdatta** [comment]
Could you please help me how to update the pull request that i made .

**Comment by nglgzz** [comment]
Yeah sure. You can make the changes, commit them and push to your master branch, and that will add the commit to this pull request. Let me know if there's anything that's unclear :)

**Comment by nglgzz** [comment]
I updated the branch to resolve the conflict and to move the entry in the correct location. 

Thank you again for your contribution @vikranthdatta :sparkles:

**Pull request merged**
