### PR TITLE
Adding Billions in Change

### PR DESCRIPTION
**Pull request by Frenzyritz13**
Added Billions in Change to Social Impact

### CODE REVIEW

**Comment by nglgzz** [comment]
Though the mission of this company is awesome, I don't think it fits in this list as it's not environment related. 

I would love to see a list with similar companies to this though :wink:

**Comment by Frenzyritz13** [comment]
Hey,

It is environment related. That company has a subsidiary, which does not
have an official website, but it manufactures energy generating cycles,
rain makers and more such products.

Here are the links to their videos
https://youtu.be/xdLIRh7Zu64
https://youtu.be/55xgcAw2coI
Please do look into this.

Thank you
Ritvi Mishra

**Comment by nglgzz** [comment]
You're right, I didn't read too in depth what they're doing. Thank you for correcting me, and thank you for the awesome video you linked! 

GitHub won't let me reopen this pull request right now, because you have another one open from the same branch of your fork. 

Feel free to re-add this change to the other pull request. Otherwise I'll just reopen this one once the other one is merged.

**Comment by nglgzz** [comment]
I manually added this entry as I didn't see any update on the other PR for a while, and it's a solid addition to the list.

**Comment by Frenzyritz13** [comment]
Hey,

I am sorry about not getting back, didnt get the time. Happy to help.

Thank you
Ritvi Mishra

**Pull request closed without merging**
